export const GETTING_POSTS_PENDING = "GETTING_POSTS_PENDING";
export const GETTING_POSTS_SUCCESS = "GETTING_POSTS_SUCCESS";
export const GETTING_POSTS_FAIL = "GETTING_POSTS_FAIL";

export const ADDING_POST_PENDING = "ADDING_POST_PENDING";
export const ADDING_POST_SUCCESS = "ADDING_POST_SUCCESS";
export const ADDING_POST_FAIL = "ADDING_POST_FAIL";